import { useEffect, useState } from "react";
import axios from "axios";
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header/Header'
import Products from '@/components/Products/Products'
import Footer from '@/components/Footer/Footer'
export default function Home() {
  const [products, setProducts] = useState([]);

  const fetchData = async () => {
    const response = await axios.get(
      "https://fb93f4a2379e42ce9993b36e98a03e97.api.mockbin.io/"
    );
    setProducts(response.data);
  };

  useEffect(() => {
    fetchData();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.wrap}>
        <Header />
        <main className={`${styles.main}`}>
          <Products products={products} />
        </main>
        <Footer />
      </div>
    </>
  )
}
